from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

b1 = KeyboardButton('1')
b2 = KeyboardButton('2')
b3 = KeyboardButton('3')
b4 = KeyboardButton('4')
b5 = KeyboardButton('5')
b6 = KeyboardButton('6')
b7 = KeyboardButton('7')
b8 = KeyboardButton('8')
b9 = KeyboardButton('9')
b10 = KeyboardButton('0')
b11 = KeyboardButton('+')
b12 = KeyboardButton('-')
b13 = KeyboardButton('*')
b14 = KeyboardButton('Pow')
b15 = KeyboardButton('%')
b16 = KeyboardButton('/')
b17 = KeyboardButton('//')
b18 = KeyboardButton(')')
b19 = KeyboardButton('(')
b20 = KeyboardButton('.')
b21 = KeyboardButton('=')

kb_calc = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=False)
kb_calc.row(b7,b8,b9,b10,b15,b16,b17).row(b4,b5,b6,b11,b13,b14,b20).row(b1,b2,b3,b12,b19,b18,b21)